-- Assign the public SSH key to the Fivetran user. The private key was entered into Fivetran when configuring the destination
ALTER USER PC_FIVETRAN_USER
SET RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn4ObTHy7EYPAyQv6anCcaloNBJfmxUWlE5jIeiMv7dq0FQcocEe24CWLIiP88gFdqWNwa/stmiu1DtTCeT8mQFa4x7hFwgJmvlN5OUK8tI+ucqyZRBhcI+vGDCud4e7p9Gq4EMP3k65PnAm/L8AhtZp2QUiW8qrJX31rrJTjmnPxNxwgfgWyI0Hq3j4gR252Hqhb6K76tQ4UqRC3smDzohZDjsXdtGUfEt2cEd6V47+P04Jo6vPkEunyGiArpwNCoT9UGng6SmMJ6DxmABYMCz3i+8eGUarxlZ6RNhvdY2emPrn0Ve74hkKRKudRNb9lsdUsK8GgppiksUrz601YoQIDAQAB';

-- Validate user creation
DESC USER PC_FIVETRAN_USER;

-- Create an internal stage to store the file results
CREATE DATABASE IF NOT EXISTS ORACLE_REPORT_DEMO;
CREATE SCHEMA IF NOT EXISTS ORACLE_REPORT_DEMO.INTERNAL_STAGES;
CREATE STAGE IF NOT EXISTS ORACLE_REPORT_DEMO.INTERNAL_STAGES.DRUG_DISCOVERY_REPORT;

-- Validate stage creation
LIST @ORACLE_REPORT_DEMO.INTERNAL_STAGES.DRUG_DISCOVERY_REPORT;
